name: hello_world_pipeline
on: push
jobs:
  hello_world_job:
    runs-on: ubuntu-24.04
    steps:
      - name: my-job
        run: echo "hello world"
        
      - name: name-job
        run: echo "NAVEENS - 24CB033"
      
